version: "3.5"

services:
  db:
    image: "postgres:10"
    restart: "always"
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "typeormtest"

  adminer:
    image: "adminer"
    restart: "always"
    ports:
      - "1337:8080"
